### ISSUE TITLE
[Weather] [Weather observed] Measuring system (Metric, Imperial, etc) is not specified

### ISSUE THREAD

**Issue by ilarimikkonen** [Fiware/dataModels#298]
looking at the specification, it is impossible to say which units are used. It would be good to state somewhere what measurement system is used. If reporter posts Fahrenheit instead of Celsius, results are hilarious

**Comment by chicco785** [comment]
@ilarimikkonen this is the role of metadata. see the example here:
https://github.com/Fiware/dataModels/blob/master/specs/Environment/AirQualityObserved/example-normalized.json

**Comment by jmcanterafonseca** [comment]
Well, what is reported in this issue is not true

temperature : Air's temperature observed.
Attribute type: Number
Default unit: Degrees centigrades.
Attribute metadata:
timestamp : optional timestamp for the observed value. It can be ommitted if the observation time is the same as the one captured by the dateObserved attribute at entity level.
Optional

**Comment by jmcanterafonseca** [comment]
closed as it has been responded.
